name: Build
on: 
  push:
  pull_request:
    types:
      [opened, synchronize]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Run Build
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: ${{ secrets.DOCKERHUB_USERNAME }}/bannerlordcoop:1.0.0
          run: |
            git clone https://github.com/${{ github.repository }}
            git checkout ${{ github.ref }}
            echo d | xcopy /e /v "BannerlordAssemblies" "BannerlordCoop\mb2\bin\Win64_Shipping_Client\"
            cd "BannerlordCoop\source"
            nuget restore Coop.sln
            msbuild Coop.sln