name: Build

on: 
  push:
  pull_request:
    types:
      [opened, synchronize]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        uses:
          ./.github/workflows/common.yml
        with:
          DOCKERHUB_USERNAME: ${{ env.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_IMAGE: ${{ env.DOCKERHUB_IMAGE }}
          
      - name: Checkout Repo
        run: |
          git clone https://github.com/${{ github.repository }}
          cd BannerlordCoop
          git checkout "${{ github.ref_name }}"

      - name: Copy Assemblies
        run: |
          cp -R /home/mb2 BannerlordCoop/mb2
          
      - name: Build Solution
        run: |
          cd BannerlordCoop/source
          dotnet build