name: Build

on: 
  push:
  pull_request:
    types:
      [opened, synchronize]
    
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: hulkhan/bannerlordcoop:1.0.1
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    steps:
          
      - name: Checkout Repo
        shell: sh
        run: |
          git clone https://github.com/${{ github.repository }}
          cd BannerlordCoop
          git checkout "${{ github.ref }}"

      - name: Copy Assemblies
        shell: pwsh
        run: |
          cp -R ../mb2 mb2
          
      - name: Build Solution
        shell: pwsh
        run: |
          cd source
          dotnet build