name: Build

on: 
  push:
  pull_request:
    types:
      [opened, synchronize]
    
jobs:
  build:
    runs-on: ubuntu-latest
    uses: hakanyildizhan/BannerlordCoop/.github/workflows/common.yml@development-net-standard
    with:
      DOCKERHUB_USERNAME: ${{ env.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_IMAGE: ${{ env.DOCKERHUB_IMAGE }}