name: Build
on: 
  push:
  pull_request:
    types:
      [opened, synchronize]
    
env:
  DOCKERHUB_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/bannerlordcoop:1.0.1
    
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Image
        run: docker image pull ${{ env.DOCKERHUB_IMAGE }}

      - name: Run Build
        shell: pwsh
        run: |
          docker run -it --rm /bin/sh ${{ env.DOCKERHUB_IMAGE }}
          git clone https://github.com/${{ github.repository }}
          cp -R mb2 "BannerlordCoop/mb2"
          cd "BannerlordCoop\source"
          git checkout ${{ github.ref }}
          dotnet build