name: Build

on: 
  push:
  pull_request:
    types:
      [opened, synchronize]
    
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: hulkhan/bannerlordcoop:1.0.1
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    steps:
          
      - name: Checkout Repo
        run: |
          git clone https://github.com/${{ github.repository }}
          cd BannerlordCoop
          git checkout "${{ github.ref_name }}"

      - name: Copy Assemblies
        run: |
          echo "Running pwd"
          pwd
          echo "Running ls1"
          ls /__w/BannerlordCoop
          echo "Running ls2"
          ls /__w/BannerlordCoop/BannerlordCoop
          echo "Running ls3"
          ls /__w/BannerlordCoop/BannerlordCoop/BannerlordCoop
          cp -R ../mb2 BannerlordCoop/mb2
          
      - name: Build Solution
        run: |
          echo "Running ls1"
          ls /__w/
          echo "Running ls2"
          ls /__w/BannerlordCoop
          echo "Running ls3"
          ls /__w/BannerlordCoop/BannerlordCoop
          echo "Running ls4"
          ls /home/runner/work/BannerlordCoop/assemblies
          echo "Running pwd"
          pwd
          echo "Running ls"
          ls
          echo "Running cd.."
          cd ..
          echo "Running ls"
          ls
          echo "Running cd assemblies"
          cd assemblies
          echo "Running pwd"
          pwd
          echo "Running ls"
          ls
          echo "Running cd BannerlordCoop/source"
          cd BannerlordCoop/source
          dotnet build