name: Build
on: 
  push:
  pull_request:
    types:
      [opened, synchronize]
  
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    
    container:
      image: $DOCKERHUB_USERNAME/bannerlordcoop:1.0.0
      credentials:
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_TOKEN
        
    steps:
      - uses: actions/checkout@v3

      - name: Pull repository
        run: git clone https://github.com/${{ github.repository }}
      
      - name: Checkout branch
        run: git checkout ${{ github.ref }}
        
      - name: Copy necessary assemblies
        run: |
          echo d | xcopy /e /v "BannerlordAssemblies" "BannerlordCoop\mb2\bin\Win64_Shipping_Client\"
          cd "BannerlordCoop\source"
          
      - name: Nuget restore
        run: nuget restore Coop.sln
        
      - name: Build solution
        run: msbuild Coop.sln