name: Build
on: 
  push:
  pull_request:
    types:
      [opened, synchronize]
    
env:
  DOCKERHUB_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/bannerlordcoop:1.0.0
    
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Image
        run: docker image pull ${{ env.DOCKERHUB_IMAGE }}

      - name: Run Build
        shell: pwsh
        run: |
          docker run -it --rm --entrypoint powershell ${{ env.DOCKERHUB_IMAGE }}
          git clone https://github.com/${{ github.repository }}
          git checkout ${{ github.ref }}
          echo d | xcopy /e /v "BannerlordAssemblies" "BannerlordCoop\mb2\bin\Win64_Shipping_Client\"
          cd "BannerlordCoop\source"
          nuget restore Coop.sln
          msbuild Coop.sln