name: Build

on: 
  push:
  pull_request:
    types:
      [opened, synchronize]
    
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: hulkhan/bannerlordcoop:1.0.1
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    steps:
          
      - name: Checkout Repo
        run: |
          git clone https://github.com/${{ github.repository }}
          cd BannerlordCoop
          git checkout "${{ github.ref_name }}"

      - name: Copy Assemblies
        run: |
          cp -R mb2 BannerlordCoop/mb2
          
      - name: Build Solution
        run: |
          cd BannerlordCoop/source
          dotnet build