name: Build
on: 
  push:
  pull_request:
    types:
      [opened, synchronize]
    
env:
  DOCKERHUB_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/bannerlordcoop:1.0.1
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Image
        run: docker image pull ${{ env.DOCKERHUB_IMAGE }}

      - name: Run Image
        shell: pwsh
        run: |
          docker run -it --rm /bin/sh ${{ env.DOCKERHUB_IMAGE }}
          
      - name: Checkout Repo
        shell: pwsh
        run: |
          git clone https://github.com/${{ github.repository }}
          cd BannerlordCoop
          branch = "git name-rev --name-only ${{ github.ref }}"
          git checkout "$branch"

      - name: Copy Assemblies
        shell: pwsh
        run: |
          cp -R ../mb2 mb2
          
      - name: Build Solution
        shell: pwsh
        run: |
          cd source
          dotnet build