apiVersion: v1
kind: Pod
metadata:
  name: private-reg
env:
  DOCKERHUB_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/bannerlordcoop:1.0.1
spec:
  containers:
    - name: private-reg-container
      image: ${{ env.DOCKERHUB_IMAGE }}
  imagePullSecrets:
    - name: ${{ secrets.DOCKERHUB_TOKEN }}

name: Build
on: 
  push:
  pull_request:
    types:
      [opened, synchronize]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      name: private-reg-container
    
    steps:
          
      - name: Checkout Repo
        shell: bash
        run: |
          git clone https://github.com/${{ github.repository }}
          cd BannerlordCoop
          branch = "git name-rev --name-only ${{ github.ref }}"
          git checkout "$branch"

      - name: Copy Assemblies
        shell: pwsh
        run: |
          cp -R ../mb2 mb2
          
      - name: Build Solution
        shell: pwsh
        run: |
          cd source
          dotnet build