name: build TestServer

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Nuget Restore
      run: nuget restore source\TestServer\TestServer.csproj

    - name: build Test Server
      run: msbuild source\TestServer\TestServer.csproj -verbosity:diag
