name: Build

on: 
  pull_request:
    types:
      [opened, synchronize]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: hulkhan/bannerlordcoop:1.0.1
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    steps:
      - name: Checkout Repo
        shell: bash
        run: |
          git clone https://github.com/${{ github.repository }}
          cd BannerlordCoop
          echo "branch=$(echo ${github.event.pull_request.base.ref#refs/heads/})"
          git fetch origin "pull/${{ github.event.number }}/head:$branch"
          git checkout "$branch"

      - name: Copy Assemblies
        run: |
          cp -R /home/mb2 BannerlordCoop/mb2
          
      - name: Build Solution
        run: |
          cd BannerlordCoop/source
          dotnet build